application: a-mind-beside-itself
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /styles
  static_dir: styles
- url: /images
  static_dir: images
- url: /scripts
  static_dir: scripts
- url: /res
  static_dir: res
- url: /.*
  script: code.py
